import httpx, base64, logging
from config import settings

logger = logging.getLogger(__name__)

async def push_to_github(repo_name: str, files: dict, token: str) -> str:
    headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github.v3+json"}
    async with httpx.AsyncClient(timeout=30) as client:
        # create repo
        resp = await client.post("https://api.github.com/user/repos", headers=headers, json={
            "name": repo_name, "description": "Generated by AI Code Manager", "private": False, "auto_init": True
        })
        if resp.status_code not in (201, 422):
            raise Exception(f"Failed to create repo: {resp.json().get('message')}")

        if resp.status_code == 422:  # exists
            user_resp = await client.get("https://api.github.com/user", headers=headers)
            user_resp.raise_for_status()
            username = user_resp.json()["login"]
            repo_full = f"{username}/{repo_name}"
        else:
            repo_full = resp.json()["full_name"]

        for filename, content in files.items():
            put_resp = await client.put(
                f"https://api.github.com/repos/{repo_full}/contents/{filename}",
                headers=headers,
                json={"message": f"Add {filename}", "content": base64.b64encode(content.encode()).decode()}
            )
            if put_resp.status_code not in (201, 200):
                logger.warning(f"Failed to push {filename}: {put_resp.json()}")

        return f"https://github.com/{repo_full}"